# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0
- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'other'
    extraProperties: |
      sonar.projectKey=marciopaulo-sonar_books
      sonar.projectName=books
      sonar.organization=marciopaulo-sonar
      sonar.sources=src/main/java
      sonar.tests=src/test/java
      sonar.java.binaries=target/classes
      sonar.java.test.binaries=target/test-classes
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install sonar:sonar'
- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'
